dbSie.define_table(
    'V_NOTAS_FINAIS_ALUNOS_DISCIPLINAS',
    Field('ANO', 'integer'),
    Field('COD_ATIV_CURRIC', 'string'),
    Field('CPF', 'string'),
    Field('CPF_PURO', 'string'),
    Field('DESCR_BAIRRO', 'string'),
    Field('DESCR_COMPLEMENTO', 'string'),
    Field('DESCR_DISTRITO', 'string'),
    Field('DESCR_ESTADO', 'string'),
    Field('DESCR_MUNICIPIO', 'string'),
    Field('DESCR_NUMERO', 'string'),
    Field('DESCR_PAIS', 'string'),
    Field('DESCR_RUA', 'string'),
    Field('DESCR_UF', 'string'),
    Field('DT_NASCIMENTO', 'date'),
    Field('FONE_CELULAR', 'string'),
    Field('FONE_RESIDENCIAL', 'string'),
    Field('FOTO', 'blob'),
    Field('ID_ALUNO', 'integer'),
    Field('ID_CURSO_ALUNO', 'integer'),
    Field('ID_DOC_CPF', 'integer'),
    Field('ID_DOC_RG', 'integer'),
    Field('ID_NATURALIDADE', 'integer'),
    Field('ID_PESSOA', 'integer'),
    Field('MATR_ALUNO', 'string'),
    Field('MEDIA_FINAL', 'float'),
    Field('NACIONALIDADE_ITEM', 'integer'),
    Field('NACIONALIDADE_TAB', 'integer'),
    Field('NO_RG', 'string'),
    Field('NOME_ATIV_CURRIC', 'string'),
    Field('NOME_MAE', 'string'),
    Field('NOME_PAI', 'string'),
    Field('NOME_PESSOA', 'string'),
    Field('NOME_UNIDADE', 'string'),
    Field('ORGAO_EMISSOR', 'string'),
    Field('PERIODO_ITEM', 'integer'),
    Field('SEXO', 'string'),
    Field('SIGLA_UNIDADE', 'string'),
    Field('URL', 'string'),
    primarykey=['ANO', 'ID_ALUNO', 'COD_ATIV_CURRIC', 'PERIODO_ITEM'],
    migrate=False,
    rname='DBSM.V_NOTAS_FINAIS_ALUNOS_DISCIPLINAS'
)