dbSie.define_table("PARTICIPANTES_PROJ",
    Field("ID_PARTICIPANTE", "integer"),
    Field("ID_PROJETO", "integer"),
    Field("ID_CURSO_ALUNO", "integer"),
    Field("ID_CONTRATO_RH", "integer"),
    Field("ID_PESSOA", "integer"),
    Field("ID_UNIDADE", "integer"),
    Field("FUNCAO_TAB", "integer"),
    Field("FUNCAO_ITEM", "integer"),
    Field("DT_INICIAL", "date"),
    Field("DT_FINAL", "date"),
    Field("CARGA_HORARIA", "integer"),
    Field("TITULACAO_TAB", "integer"),
    Field("TITULACAO_ITEM", "integer"),
    Field("SITUACAO", "string"),
    Field("PARTICIPANTES_PROJ", "string"),
    Field("OBS_PARTICIPANTE", "integer"),
    Field("COD_OPERADOR", "integer"),
    Field("DT_ALTERACAO", "date"),
    Field("HR_ALTERACAO", "time"),
    Field("CONCORRENCIA", "integer"),
    Field("DESCR_MAIL", "string"),
    Field("ID_BOLSISTA", "integer"),
    Field("CH_SUGERIDA", "integer"),
    Field("ID_ENT_EXTERNA", "integer"),
    Field("LINK_LATTES", "string"),
    Field("ID_PROJ_SOLICIT", "integer"),
    Field("ID_PARTICIP_SUBST", "integer"),
    Field("ENDERECO_FISICO", "string"),
    primarykey=["ID_PARTICIPANTE"],
    migrate=False
)