dbSie.define_table('V_FUNCIONARIOS',
                   Field('AGENCIA_FGTS'),
                   Field('AGENCIA_PGTO'),
                   Field('BANCO_FGTS'),
                   Field('BANCO_PGTO'),
                   Field('CATEGORIA_ITEM', 'integer'),
                   Field('CATEGORIA_TAB', 'integer'),
                   Field('CCORRENTE_FGTS'),
                   Field('CCORRENTE_PGTO'),
                   Field('COD_CARGO'),
                   Field('COD_ESTR_CARGO'),
                   Field('COD_FONTE', 'integer'),
                   Field('COD_GESTORA', 'integer'),
                   Field('COD_LOT_EXERC'),
                   Field('COD_LOT_OFICIAL'),
                   Field('COD_LOT_VINC'),
                   Field('COD_PLANO'),
                   Field('COD_PROGRAMA'),
                   Field('COD_UO', 'integer'),
                   Field('CODIGO_VAGA', 'integer'),
                   Field('CPF'),
                   Field('DEFICIENCIA_ITEM', 'integer'),
                   Field('DEFICIENCIA_TAB', 'integer'),
                   Field('DESCR_AGENCIA_PGTO'),
                   Field('DESCR_BANCO_PGTO'),
                   Field('DESCR_CARGO'),
                   Field('DESCR_CATEGORIA'),
                   Field('DESCR_CHEFIA_EXERC'),
                   Field('DESCR_CHEFIA_OF'),
                   Field('DESCR_DEFICIENCIA'),
                   Field('DESCR_ESCOLARIDADE'),
                   Field('DESCR_ESFERA'),
                   Field('DESCR_ESTADO_CIVIL'),
                   Field('DESCR_ETNIA'),
                   Field('DESCR_FONTE'),
                   Field('DESCR_FORMAINGRESSO'),
                   Field('DESCR_GESTAO'),
                   Field('DESCR_GESTORA'),
                   Field('DESCR_JORNADA_TRAB'),
                   Field('DESCR_LOT_EXERC'),
                   Field('DESCR_LOT_OFICIAL'),
                   Field('DESCR_LOT_VINC'),
                   Field('DESCR_MAIL'),
                   Field('DESCR_NACIONALIDADE'),
                   Field('DESCR_NATURALIDADE'),
                   Field('DESCR_PLANO'),
                   Field('DESCR_PROGRAMA'),
                   Field('DESCR_REG_JURIDICO'),
                   Field('DESCR_SITUACAO'),
                   Field('DESCR_TIPO_ADMISSAO'),
                   Field('DESCR_TIPO_CONTRATO'),
                   Field('DESCR_TIPO_DESLIGA'),
                   Field('DESCR_TIPO_VINCULO'),
                   Field('DESCR_UO'),
                   Field('DIGITO_VERIF', 'integer'),
                   Field('DT_ADMISSAO_CARGO', 'date'),
                   Field('DT_ADMISSAO_INST', 'date'),
                   Field('DT_ADMISSAO_SP', 'date'),
                   Field('DT_APOSENTADORIA', 'date'),
                   Field('DT_DEMISSAO', 'date'),
                   Field('DT_DESLIGAMENTO', 'date'),
                   Field('DT_EXPEDICAO_CI', 'date'),
                   Field('DT_NASCIMENTO', 'date'),
                   Field('DT_NOMEACAO', 'date'),
                   Field('DT_OPCAO_FGTS', 'date'),
                   Field('DT_POSSE', 'date'),
                   Field('DT_ULT_AVANCO', 'date'),
                   Field('ESCOLARIDADE_ITEM', 'integer'),
                   Field('ESCOLARIDADE_TAB', 'integer'),
                   Field('ESFERA_ITEM', 'integer'),
                   Field('ESFERA_TAB', 'integer'),
                   Field('ESTADO_CIVIL_ITEM', 'integer'),
                   Field('ESTADO_CIVIL_TAB', 'integer'),
                   Field('ETNIA_ITEM', 'integer'),
                   Field('ETNIA_TAB', 'integer'),
                   Field('FATOR_RH'),
                   Field('FORMAINGRESSO_ITEM', 'integer'),
                   Field('FORMAINGRESSO_TAB', 'integer'),
                   Field('GESTAO_ITEM', 'integer'),
                   Field('GESTAO_TAB', 'integer'),
                   Field('GRUPO_CARGO_ITEM', 'integer'),
                   Field('ID_CARGO', 'integer'),
                   Field('ID_CHEFE_EXERC', 'integer'),
                   Field('ID_CHEFE_OF', 'integer'),
                   Field('ID_CHEFIA_EXERC', 'integer'),
                   Field('ID_CHEFIA_OF', 'integer'),
                   Field('ID_CONTRATO_RH', 'integer'),
                   Field('ID_ESPACO', 'integer'),
                   Field('ID_FONTE_RECURSO', 'integer'),
                   Field('ID_FUNCIONARIO', 'integer'),
                   Field('ID_LOT_EXERC', 'integer'),
                   Field('ID_LOT_OFICIAL', 'integer'),
                   Field('ID_LOT_VINC', 'integer'),
                   Field('ID_NATURALIDADE', 'integer'),
                   Field('ID_PESSOA', 'integer'),
                   Field('ID_PLANO', 'integer'),
                   Field('ID_PROGRAMA', 'integer'),
                   Field('ID_SUBST_EXERC', 'integer'),
                   Field('ID_SUBST_OF', 'integer'),
                   Field('ID_TURNO_RH', 'integer'),
                   Field('ID_UNIDADE_GESTORA', 'integer'),
                   Field('ID_UNIDADE_ORC', 'integer'),
                   Field('IND_ISENCAO_IR'),
                   Field('IND_PROBATORIO'),
                   Field('IND_SUSPENSAO_PGTO'),
                   Field('JORNADA_TRAB_ITEM', 'integer'),
                   Field('JORNADA_TRAB_TAB', 'integer'),
                   Field('MATR_EXTERNA', 'integer'),
                   Field('MATR_UNICA', 'integer'),
                   Field('NACIONALIDADE_ITEM', 'integer'),
                   Field('NACIONALIDADE_TAB', 'integer'),
                   Field('NOME_FUNCIONARIO'),
                   Field('NOME_MAE'),
                   Field('NOME_PAI'),
                   Field('NUM_AVANCOS', 'integer'),
                   Field('NUM_CI'),
                   Field('NUM_CPF'),
                   Field('NUM_CT'),
                   Field('NUM_TITULO'),
                   Field('ORGAO_EMISSOR_CI'),
                   Field('PIS_PASEP'),
                   Field('REG_JURIDICO_ITEM', 'integer'),
                   Field('REG_JURIDICO_TAB', 'integer'),
                   Field('SEXO'),
                   Field('SIGLA_CATEGORIA'),
                   Field('SIGLA_DEFICIENCIA'),
                   Field('SIGLA_ESCOLARIDADE'),
                   Field('SIGLA_ESTADO_CIVIL'),
                   Field('SIGLA_ETNIA'),
                   Field('SIGLA_FORMAINGRESSO'),
                   Field('SIGLA_JORNADA_TRAB'),
                   Field('SIGLA_NACIONALIDADE'),
                   Field('SIGLA_REG_JURIDICO'),
                   Field('SIGLA_SITUACAO'),
                   Field('SITUACAO_ITEM', 'integer'),
                   Field('SITUACAO_TAB', 'integer'),
                   Field('TEMPO_SERVICO', 'integer'),
                   migrate=False,
                   primarykey=['ID_CONTRATO_RH'],
                   rname='DBSM.V_FUNCIONARIOS'
)