dbSie.define_table("V_PROJETOS",
    Field("UNIDADE_RESPONSAVEL", "string"),
    Field("TITULO", "string"),
    Field("RESUMO", "text"),
    Field("ID_PROJETO", "integer"),
    Field("DT_INICIAL", "date"),
    Field("DT_FINAL", "date"),
    Field("DESCR_MAIL", "string"),
    Field("COORDENADOR", "string"),
    Field("ANO_REFERENCIA", "integer"),
    Field("NUMERO_PROCESSO", "string"),
    Field("ID_DOCUMENTO", "integer"),
    Field("DESCR_SITUACAO", "string"),
    Field("DESCR_FUNDACAO", "string"),
    Field("GRUPO_CNPQ", "string"),
    primarykey=["ID_PROJETO"],
    migrate=False,
    rname='DBSM.V_PROJETOS'
)