# -*- coding: utf-8 -*-
dbSie.define_table("V_CHEFIAS_IMEDIATAS",
                   Field("NOME_SERVIDOR", "string"),
                   Field("CARGO_SERVIDOR", "string"),
                   Field("ID_UNIDADE", "integer"),
                   Field("UNIDADE_EXERCICIO_CHEFIA", "string"),
                   Field("UNIDADE_EXERCICIO_SERVIDOR", "string"),
                   Field("CHEFIA_TITULAR", "string"),
                   # Field("CHEFIA_SUBSTITUTA", "string"),
                   Field("SIAPE_SERVIDOR", "integer"),
                   Field("SIAPE_CHEFIA_TITULAR", "integer"),
                   # Field("SIAPE_CHEFIA_SUBST", "integer"),
                   Field("CPF_SERVIDOR_MASCARA", "string"),
                   Field("CPF_SERVIDOR", "string"),
                   Field("EMAIL_SERVIDOR", "string"),
                   Field("EMAIL_CHEFIA_TITULAR", "string"),
                   # Field("EMAIL_CHEFIA_SUBST", "string"),
                   Field("CPF_CHEFIA_MASCARA", "string"),
                   Field("CPF_CHEFIA", "string"),
                   primarykey=["SIAPE_SERVIDOR"],
                   migrate=False,
                   rname="DBSM.V_CHEFIAS_IMEDIATAS"
                   )
