# -*- coding: utf-8 -*-

dbSie.define_table("OCOR_FUNCIONAIS_RH",
                   Field("ID_OCOR_FUNCIONAL", "integer"),
                   Field("ID_CONTRATO_RH", "integer"),
                   Field("ID_COD_FUNCIONAL", "string"),
                   Field("DT_INICIO", "date"),
                   Field("DT_TERMINO", "date"),
                   Field("NUM_DIAS", "float"),
                   Field("NUM_PORTARIA", "string"),
                   Field("DT_PORTARIA", "date"),
                   Field("NUM_PROCESSO", "string"),
                   Field("DT_DOU", "date"),
                   Field("ID_AREA_CONHEC", "integer"),
                   Field("ID_DOCUMENTO", "integer"),
                   Field("OBSERVACOES", "string"),
                   Field("ID_CID", "integer"),
                   Field("ID_CHEFIA", "integer"),
                   Field("ID_LOCAL_CHEFIA", "integer"),
                   Field("ID_LOCAL_ORIGEM", "integer"),
                   Field("LOCAL_ORIGEM_TAB", "integer"),
                   Field("LOCAL_ORIGEM_ITEM", "integer"),
                   Field("ID_LOCAL_DESTINO", "integer"),
                   Field("LOCAL_DESTINO_ITEM", "integer"),
                   Field("LOCAL_DESTINO_TAB", "integer"),
                   Field("ID_CARGO_ANT", "integer"),
                   Field("ID_PLANO_ANT", "integer"),
                   Field("ID_CARGO_NOVO", "integer"),
                   Field("ID_PLANO_NOVO", "integer"),
                   Field("QT_REFERENCIA", "float"),
                   Field("VL_REFERENCIA", "float"),
                   Field("PC_REFERENCIA", "float"),
                   Field("IND_SITUACAO", "string"),
                   Field("MES_REF_TAB", "integer"),
                   Field("MES_REF_ITEM", "integer"),
                   Field("ANO_REF", "integer"),
                   Field("COD_TABELA_ANT", "integer"),
                   Field("ITEM_TABELA_ANT", "integer"),
                   Field("COD_TABELA_NOVA", "integer"),
                   Field("ITEM_TABELA_NOVA", "integer"),
                   Field("OBSERVACAO", "text"),
                   Field("COD_OPERADOR", "integer"),
                   Field("DT_ALTERACAO", "date"),
                   Field("HR_ALTERACAO", "time"),
                   Field("CONCORRENCIA", "integer"),
                   Field("ID_OCOR_REF", "integer"),
                   Field("ID_PROGRAMA", "integer"),
                   Field("ID_CHEFIA_VAGA", "integer"),
                   Field("ID_CARGO_VAGA", "integer"),
                   Field("ENDERECO_FISICO", "string"),
                   primarykey=["ID_OCOR_FUNCIONAL"],
                   migrate=False)