dbSie.define_table('CLASSIFICACOES_PRJ',
                   Field('ID_CLASSIFICACAO', 'integer'),
                   Field('CLASSIFICACAO_TAB', 'integer'),
                   Field('CLASSIFICACAO_ITEM', 'integer'),
                   Field('DESCRICAO', 'string'),
                   Field('CODIGO', 'string'),
                   Field('ID_CLASSIF_SUP', 'integer'),
                   Field('OBSERVACAO', 'string'),
                   Field('ID_TIPO_DOC', 'integer'),
                   Field('COD_OPERADOR', 'integer'),
                   Field('DT_ALTERACAO', 'date'),
                   Field('HR_ALTERACAO', 'time'),
                   Field('CONCORRENCIA', 'integer'),
                   Field('ID_TIPO_DOC_AVAL', 'integer'),
                   Field('ID_TIPO_DOC_PUB', 'integer'),
                   Field('IND_ATIVO', 'string'),
                   Field('CERTIFICADO_TAB', 'integer'),
                   Field('CERTIFICADO_ITEM', 'integer'),
                   Field('ENDERECO_FISICO', 'string'),
                   primarykey=['ID_CLASSIFICACAO'],
                   migrate=False
                   )
