# -*- coding: utf-8 -*-

dbSie.define_table("TRAMITACOES",
                   Field("ID_TRAMITACAO", "integer"),
                   Field("SEQUENCIA", "integer"),
                   Field("ID_DOCUMENTO", "integer"),
                   Field("TIPO_ORIGEM", "integer"),
                   Field("ID_ORIGEM", "integer"),
                   Field("TIPO_DESTINO", "integer"),
                   Field("ID_DESTINO", "integer"),
                   Field("DT_ENVIO", "date"),
                   Field("DT_RECEBIMENTO", "date"),
                   Field("DT_VALIDADE", "date"),
                   Field("DESPACHO", "string"),
                   Field("SITUACAO_TRAMIT", "string"),
                   Field("IND_RETORNO_OBRIG", "string"),
                   Field("ID_FLUXO", "integer"),
                   Field("COD_OPERADOR", "integer"),
                   Field("DT_ALTERACAO", "date"),
                   Field("HR_ALTERACAO", "time"),
                   Field("CONCORRENCIA", "integer"),
                   Field("ID_USUARIO_INFO", "integer"),
                   Field("DT_DESPACHO", "date"),
                   Field("HR_DESPACHO", "time"),
                   Field("HR_RECEBIMENTO", "time"),
                   Field("PRIORIDADE_TAB", "integer"),
                   Field("PRIORIDADE_ITEM", "integer"),
                   Field("ID_APLIC_ACAO", "integer"),
                   Field("DESPACHO_RTF", "clob"),
                   Field("ENDERECO_FISICO", "string"),
                   primarykey=["ID_TRAMITACAO"],
                   migrate=False)


