# -*- coding: utf-8 -*-
# Não traz resumo por ser campo CLOB
dbSie.define_table("PROJETOS",
                   Field("ID_PROJETO", "integer"),
                   Field("ID_DOCUMENTO", "integer"),
                   Field("NUM_PROCESSO", "string"),
                   Field("TITULO", "string"),
                   Field("DT_INICIAL", "date"),
                   Field("DT_CONCLUSAO", "date"),
                   Field("DT_REGISTRO", "date"),
                   Field("TIPO_PUBLICO_TAB", "integer"),
                   Field("TIPO_PUBLICO_ITEM", "integer"),
                   Field("PUBLICO_ALVO", "integer"),
                   Field("PUBLICO_ENVOLVIDO", "integer"),
                   Field("VL_PREVISTO", "float"),
                   Field("OBSERVACOES", "string"),
                   Field("COD_OPERADOR", "string"),
                   Field("DT_ALTERACAO", "date"),
                   Field("HR_ALTERACAO", "time"),
                   Field("CONCORRENCIA", "integer"),
                   Field("AVALIACAO_TAB", "integer"),
                   Field("AVALIACAO_ITEM", "integer"),
                   Field("SITUACAO_TAB", "integer"),
                   Field("SITUACAO_ITEM", "integer"),
                   Field("DT_ULTIMA_AVAL", "date"),
                   Field("ID_CLASSIFICACAO", "integer"),
                   Field("ACESSO_PARTICIP", "string"),
                   Field("ID_PROJETO_SUP", "integer"),
                   Field("FUNDACAO_TAB", "integer"),
                   Field("FUNDACAO_ITEM", "integer"),
                   Field("ID_RH_GESTOR", "integer"),
                   Field("EVENTO_TAB", "integer"),
                   Field("EVENTO_ITEM", "integer"),
                   Field("ALUNOS_MATRIC", "integer"),
                   Field("ALUNOS_CONCLUINT", "integer"),
                   Field("PAGA_BOLSA", "string"),
                   Field("VL_BOLSA", "float"),
                   Field("ID_BOLSA", "integer"),
                   Field("PALAVRA_CHAVE01", "string"),
                   Field("PALAVRA_CHAVE02", "string"),
                   Field("PALAVRA_CHAVE03", "string"),
                   Field("PALAVRA_CHAVE04", "string"),
                   Field("CARGA_HORARIA", "integer"),
                   Field("AI", "integer"),
                   Field("ENDERECO_FISICO", "string"),
                   primarykey=["ID_PROJETO"],
                   migrate=False)